version: '3'

services:
  mirror:
    build: .
    volumes:
      - ./projects:/home/node/projects:z
      - ./src:/home/node/src:z
  nexus:
    image: sonatype/nexus3
    volumes:
      - ${NEXUS_DATA_DIR}:/nexus-data:z
    ports:
      - "8081:8081"
